Add Admin Boundaries Section to Data Layers
DigitalCommons/land-explorer-front-end pull request #189
Opened 2023-03-14 12:24 UTC by King-Mob

#### What? Why?

Closes #170 

Connects to uploaded tilesets on mapbox to provide new overlays showing administrative boundaries

#### What should we test?

Select the data layers section
scroll to administrative boundaries
toggle the various new layers

#### Release notes

#### Deployment notes

Nope

2023-03-14 21:29 UTC, rogup requested changes
All looks good, just 1 minor comment

2023-03-14 21:29 UTC, rogup commented on src/components/MapLayers.js
> +        console.log(landDataLayers)
Sorry this is quite pedantic, but please could we add a message to this log to indicate what it is, or remove the log if it's not needed anymore? There is lots of data that gets logged to the console without any context, which makes it more difficult to debug elsewhere.

2023-03-15 14:31 UTC, King-Mob commented
@rogup No worries, I was using the log to debug, removed it now

2023-03-15 14:31 UTC, merged

2023-03-23 11:49 UTC, lin-d-hop commented
This is looking great @King-Mob Amazing work!
I think there might be some tweaks but I'd be happy to merge this.
I'll just check in with Kate first.